const CACHE='velnar-radar-v17';
const SHELL=['./','./index.html','./article.html','./manifest.webmanifest','./assets/velnar-symbol.svg','./assets/radar-qr.svg','./assets/qrcode.min.js','./assets/qrcodejs.LICENSE.txt','./assets/share-export-fix.js','./news.json'];
const NEWS_URL=new URL('./news.json',self.registration.scope).href;
const SHARE_EXPORT_LOADER="\n;(function(){if(document.querySelector('script[data-velnar-share-export]'))return;var s=document.createElement('script');s.src='./assets/share-export-fix.js';s.async=false;s.setAttribute('data-velnar-share-export','1');document.head.appendChild(s)})();";

const THEME_META='<meta name="color-scheme" content="light dark"><meta name="theme-color" media="(prefers-color-scheme: light)" content="#f3f4f7"><meta name="theme-color" media="(prefers-color-scheme: dark)" content="#111318">';

const COMMON_STYLE=`<style id="velnar-theme-v17">
.brandbar{top:0!important;border:0!important;border-bottom:1px solid rgba(17,18,20,.075)!important;border-radius:0!important;background:#f3f4f7!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
.velnar-theme-select{appearance:auto;min-height:32px;border:1px solid var(--line);border-radius:999px;background:var(--bg);color:var(--text);padding:5px 10px;font:600 10px/1.2 -apple-system,BlinkMacSystemFont,"SF Pro Text","PingFang SC","Helvetica Neue",Arial,sans-serif;outline:none;cursor:pointer}.velnar-theme-select:focus-visible{box-shadow:0 0 0 3px rgba(57,110,227,.16),0 0 0 1px rgba(57,110,227,.48)}.velnar-theme-wrap{display:flex;align-items:center;gap:10px}
@media(max-width:640px){.velnar-theme-select{max-width:78px;min-height:34px;padding:5px 7px;font-size:9.5px}.velnar-theme-wrap{gap:6px}.mode{display:none!important}}
@media(prefers-color-scheme:dark){html:not([data-theme="light"]){--bg:#111318;--card:#181a20;--text:#f2f3f5;--muted:#969aa5;--line:#2a2d35;--line-strong:#393d47;--brand:#f2f4ff;--soft:#17191f;--accent:#7f9cff;color-scheme:dark}}
html[data-theme="dark"]{--bg:#111318;--card:#181a20;--text:#f2f3f5;--muted:#969aa5;--line:#2a2d35;--line-strong:#393d47;--brand:#f2f4ff;--soft:#17191f;--accent:#7f9cff;color-scheme:dark}
html[data-theme="light"]{--bg:#f3f4f7;--card:#fff;--text:#111214;--muted:#767781;--line:#e3e5ea;--line-strong:#d7d9e1;--brand:#080c43;--soft:#f8f8fa;--accent:#396ee3;color-scheme:light}
@media(prefers-color-scheme:dark){html:not([data-theme="light"]) body,html:not([data-theme="light"]){background:#111318!important;color:#f2f3f5!important}html:not([data-theme="light"]) .brandbar{background:#111318!important;border-bottom-color:rgba(255,255,255,.085)!important}}
html[data-theme="dark"],html[data-theme="dark"] body{background:#111318!important;color:#f2f3f5!important}html[data-theme="dark"] .brandbar{background:#111318!important;border-bottom-color:rgba(255,255,255,.085)!important}
@media(prefers-color-scheme:dark){html:not([data-theme="light"]) .brandname{color:#f3f5ff!important}html:not([data-theme="light"]) .brandtag,html:not([data-theme="light"]) .product,html:not([data-theme="light"]) .mode,html:not([data-theme="light"]) .archive-mark{color:#9297a3!important}html:not([data-theme="light"]) .mobile-open,html:not([data-theme="light"]) .control,html:not([data-theme="light"]) .velnar-theme-select{background:#191c22!important;border-color:#30343d!important;color:#e7e9ee!important}html:not([data-theme="light"]) .stat,html:not([data-theme="light"]) .list,html:not([data-theme="light"]) .article,html:not([data-theme="light"]) .toc,html:not([data-theme="light"]) .archive-link{background:#17191f!important;border-color:#2a2d35!important;box-shadow:none!important}html:not([data-theme="light"]) .item{border-color:#292c34!important;color:#eceef2!important}html:not([data-theme="light"]) .read .item{background:#14161b!important}html:not([data-theme="light"]) .title,html:not([data-theme="light"]) .article h1,html:not([data-theme="light"]) .stat-value{color:#eff1f4!important}html:not([data-theme="light"]) .hero p,html:not([data-theme="light"]) .hero-note,html:not([data-theme="light"]) .section-desc,html:not([data-theme="light"]) .section-count,html:not([data-theme="light"]) .meta,html:not([data-theme="light"]) .theme,html:not([data-theme="light"]) .legend,html:not([data-theme="light"]) .themes,html:not([data-theme="light"]) .reading-meta{color:#9599a4!important}html:not([data-theme="light"]) .deck,html:not([data-theme="light"]) .body{color:#d9dce2!important}html:not([data-theme="light"]) .question{background:#202229!important;border-color:#2d3038!important}html:not([data-theme="light"]) .sources a{border-color:#2a2d35!important;color:#dfe1e6!important}html:not([data-theme="light"]) .share-shell,html:not([data-theme="light"]) .qr-card{background:#17191f!important;border-color:#2a2d35!important;color:#e7e9ee!important}html:not([data-theme="light"]) .share-action,html:not([data-theme="light"]) .share-close,html:not([data-theme="light"]) .qr-close,html:not([data-theme="light"]) .qr-action{background:#20232a!important;border-color:#343842!important;color:#e7e9ee!important}}
html[data-theme="dark"] .brandname{color:#f3f5ff!important}html[data-theme="dark"] .brandtag,html[data-theme="dark"] .product,html[data-theme="dark"] .mode,html[data-theme="dark"] .archive-mark{color:#9297a3!important}html[data-theme="dark"] .mobile-open,html[data-theme="dark"] .control,html[data-theme="dark"] .velnar-theme-select{background:#191c22!important;border-color:#30343d!important;color:#e7e9ee!important}html[data-theme="dark"] .stat,html[data-theme="dark"] .list,html[data-theme="dark"] .article,html[data-theme="dark"] .toc,html[data-theme="dark"] .archive-link{background:#17191f!important;border-color:#2a2d35!important;box-shadow:none!important}html[data-theme="dark"] .item{border-color:#292c34!important;color:#eceef2!important}html[data-theme="dark"] .read .item{background:#14161b!important}html[data-theme="dark"] .title,html[data-theme="dark"] .article h1,html[data-theme="dark"] .stat-value{color:#eff1f4!important}html[data-theme="dark"] .hero p,html[data-theme="dark"] .hero-note,html[data-theme="dark"] .section-desc,html[data-theme="dark"] .section-count,html[data-theme="dark"] .meta,html[data-theme="dark"] .theme,html[data-theme="dark"] .legend,html[data-theme="dark"] .themes,html[data-theme="dark"] .reading-meta{color:#9599a4!important}html[data-theme="dark"] .deck,html[data-theme="dark"] .body{color:#d9dce2!important}html[data-theme="dark"] .question{background:#202229!important;border-color:#2d3038!important}html[data-theme="dark"] .sources a{border-color:#2a2d35!important;color:#dfe1e6!important}html[data-theme="dark"] .share-shell,html[data-theme="dark"] .qr-card{background:#17191f!important;border-color:#2a2d35!important;color:#e7e9ee!important}html[data-theme="dark"] .share-action,html[data-theme="dark"] .share-close,html[data-theme="dark"] .qr-close,html[data-theme="dark"] .qr-action{background:#20232a!important;border-color:#343842!important;color:#e7e9ee!important}
.share-card{background:#fff!important;color:#111214!important;color-scheme:light}.share-card .share-brand-name{color:#080c43!important}.share-card .share-title{color:#111214!important}.share-card .share-product,.share-card .share-card-meta,.share-card .share-deck,.share-card .share-url,.share-card .share-qr-copy{color:#777983!important}.share-card .share-qr,.qr-code{background:#fff!important;color-scheme:light}
</style>`;

const THEME_SCRIPT=`<script id="velnar-theme-runtime-v17">(function(){var K='velnar-radar-theme-v1';function get(){try{var v=localStorage.getItem(K);return v==='light'||v==='dark'||v==='system'?v:'system'}catch(e){return'system'}}function apply(v){if(v!=='light'&&v!=='dark')v='system';if(v==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.setAttribute('data-theme',v);var m=document.getElementById('velnar-theme-color-manual');if(v==='system'){if(m)m.remove()}else{if(!m){m=document.createElement('meta');m.id='velnar-theme-color-manual';m.name='theme-color';document.head.appendChild(m)}m.content=v==='dark'?'#111318':'#f3f4f7'}var s=document.getElementById('velnarThemeSelect');if(s)s.value=v}window.setVelnarTheme=function(v){try{localStorage.setItem(K,v)}catch(e){}apply(v)};apply(get());document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('velnarThemeSelect');if(s){s.value=get();s.addEventListener('change',function(){window.setVelnarTheme(this.value)})}});window.addEventListener('storage',function(e){if(e.key===K)apply(get())})})();</script>`;

function picker(isArticle){return '<select id="velnarThemeSelect" class="velnar-theme-select" aria-label="页面外观"><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select>'}

function decorateHtml(res,isArticle){
  if(!res)return Promise.resolve(res);
  const type=res.headers.get('content-type')||'';
  if(!type.includes('text/html'))return Promise.resolve(res);
  return res.text().then(text=>{
    text=text.replace('<meta name="theme-color" content="#f3f4f7">',THEME_META);
    if(!text.includes('velnar-theme-v17')) text=text.replace('</head>',COMMON_STYLE+THEME_SCRIPT+'</head>');
    if(!text.includes('id="velnarThemeSelect"')){
      if(isArticle){
        text=text.replace('<span class="mode">Research note</span>','<div class="velnar-theme-wrap"><span class="mode">Research note</span>'+picker(true)+'</div>');
      }else{
        text=text.replace('<span class="archive-mark">Research archive</span>','<span class="archive-mark">Research archive</span>'+picker(false));
      }
    }
    const headers=new Headers(res.headers);headers.set('Content-Type','text/html; charset=utf-8');headers.set('Cache-Control','no-store');headers.delete('Content-Length');return new Response(text,{status:res.status,statusText:res.statusText,headers});
  });
}

self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});await Promise.all(clients.map(c=>{try{return c.navigate(c.url)}catch(e){return null}}))})())});
self.addEventListener('fetch',event=>{
  const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==location.origin)return;
  if(url.pathname.endsWith('/news.json')){event.respondWith(fetch(req).then(res=>{if(res.ok)caches.open(CACHE).then(c=>c.put(NEWS_URL,res.clone()));return res}).catch(()=>caches.match(NEWS_URL)));return}
  if(url.pathname.endsWith('/assets/qrcode.min.js')){event.respondWith((async()=>{let res=null;try{const fresh=await fetch(req);if(fresh.ok){res=fresh;caches.open(CACHE).then(c=>c.put(req,fresh.clone()))}}catch{}if(!res)res=await caches.match(req);if(!res)return new Response('/* QRCode unavailable */',{status:503,headers:{'Content-Type':'application/javascript; charset=utf-8'}});const text=await res.text();return new Response(text+SHARE_EXPORT_LOADER,{status:res.status,statusText:res.statusText,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store'}})})());return}
  if(req.mode==='navigate'){const isArticle=url.pathname.endsWith('/article.html'),fallback=isArticle?'./article.html':'./index.html';event.respondWith((async()=>{let res=null;try{const fresh=await fetch(req,{cache:'no-store'});if(fresh.ok){res=fresh;caches.open(CACHE).then(c=>c.put(req,fresh.clone()))}}catch{}if(!res)res=await caches.match(req).then(hit=>hit||caches.match(fallback));return decorateHtml(res,isArticle)})());return}
  event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(res=>{if(res.ok)caches.open(CACHE).then(c=>c.put(req,res.clone()));return res})));
});